#!/usr/bin/env python
import readline
import sys
import pty
import subprocess
import os
import select
import time
import string

# idl cmds for tab completion
idl_cmds = [
	'print',
	'indgen',
	'.compile',
	'help',
	'ptrarr',
	'online_help']

idl_exe = '/home/vitor/workspace/rsi/idl_6.3/bin/idl'


def completer(text, state):
	options = [i for i in idl_cmds if i.startswith(text)]
	if state < len(options):
		return options[state]

	return None

#TODO: fill 'idl_cmds' with idl cmds
#TODO: see how to include cmds with a dot at the beginning for tab completion

# initialize readline with customized tab completion support
readline.parse_and_bind("tab: complete")
readline.set_completer(completer)

# init idl as subprocess and communicate with it through pty
(master, slave) = pty.openpty()
p = subprocess.Popen([idl_exe], close_fds=True, shell=False, stdin=slave, stdout=slave, stderr=slave)


def write_idl(input):
	os.write(master, input + '\r\n')


def read_idl():
	output = ''

	r, w, e = select.select([master], [], [], 0.05) # check for available output
	while r != []:
		output += os.read(master, 10) # blocking read
		r, w, e = select.select([master], [], [], 0.05) # check for available output

	return output


def handle_input(input):

	if input is None:
		return ''

	# check executive command
	if input.lstrip().startswith('.'): # executive cmd
		return None #TODO: treat executive command accordingly

	return input


def handle_output(output):
	osl = output.splitlines()
	#osl[0] is IDL echo of input sent through stderr
	#osl[len(osl)-2] is IDL prompt ('IDL> ') sent through stderr
	#osl[len(osl)-1] is IDL prompt ('IDL> ') sent through stderr

	ho = osl[1:len(osl)-2] # handled output
	po = string.join(ho, '\n') # partial output

	#TODO: customize output text

	return po + '\n'


 # wait idl initialize
time.sleep(0.3)

# read any initial output
sys.stdout.write(read_idl())
sys.stdout.write('\n')
sys.stdout.flush()

c = True
while c:
	input = None

	try:
		input = raw_input("IDL> ")
	except:
		write_idl('exit')
		print 'exit'
		p.wait()
		c = False

	input = handle_input(input)

	if len(input) > 0:
		write_idl(input)
		output = read_idl()

		output = handle_output(output)
		
		sys.stdout.write(output)
		sys.stdout.flush()

		if input == 'exit':
			p.wait()
			c = False

print '' # line feed
